

eventos.sources  = src1
eventos.channels = ch-flink
eventos.sinks     = sink-flink

eventos.sources.src1.type = exec
eventos.sources.src1.command = python3 -u /mnt/c/big-data-ecommerce/gerador/gerador.py
eventos.sources.src1.channels = ch-flink

eventos.channels.ch-flink.type = memory
eventos.channels.ch-flink.capacity = 10000
eventos.channels.ch-flink.transactionCapacity = 1000

eventos.sinks.sink-flink.type = file_roll
eventos.sinks.sink-flink.channel = ch-flink
eventos.sinks.sink-flink.sink.directory = /mnt/c/big-data-ecommerce/flume/staging
eventos.sinks.sink-flink.sink.rollInterval = 0
eventos.sinks.sink-flink.sink.serializer = TEXT

