# ==============================
# AGENTE FLUME
# ==============================

eventos.sources = src1
eventos.channels = ch-flink ch-hdfs
eventos.sinks = sink-flink sink-hdfs


# ==============================
# SOURCE - GERADOR PYTHON
# ==============================

eventos.sources.src1.type = exec
eventos.sources.src1.command = python3 -u ${env:REPO_ROOT}/gerador/gerador.py

# Cada evento serÃƒÂ¡ enviado para os dois canais
eventos.sources.src1.channels = ch-flink ch-hdfs
eventos.sources.src1.selector.type = replicating


# ==============================
# CANAL PARA FLINK
# ==============================

eventos.channels.ch-flink.type = memory
eventos.channels.ch-flink.capacity = 10000
eventos.channels.ch-flink.transactionCapacity = 1000


# ==============================
# CANAL PARA HDFS
# ==============================

eventos.channels.ch-hdfs.type = memory
eventos.channels.ch-hdfs.capacity = 10000
eventos.channels.ch-hdfs.transactionCapacity = 1000


# ==============================
# SINK PARA FLINK / STAGING
# ==============================

eventos.sinks.sink-flink.type = file_roll
eventos.sinks.sink-flink.channel = ch-flink

eventos.sinks.sink-flink.sink.directory = ${env:REPO_ROOT}/flume/staging
eventos.sinks.sink-flink.sink.rollInterval = 0
eventos.sinks.sink-flink.sink.serializer = TEXT


# ==============================
# SINK PARA HDFS
# ==============================

eventos.sinks.sink-hdfs.type = hdfs
eventos.sinks.sink-hdfs.channel = ch-hdfs

eventos.sinks.sink-hdfs.hdfs.path = hdfs://${env:HDFS_HOST}:9000/ecommerce/raw/eventos

eventos.sinks.sink-hdfs.hdfs.filePrefix = eventos-
eventos.sinks.sink-hdfs.hdfs.fileSuffix = .jsonl

eventos.sinks.sink-hdfs.hdfs.fileType = DataStream
eventos.sinks.sink-hdfs.hdfs.writeFormat = Text

eventos.sinks.sink-hdfs.hdfs.rollInterval = 30
eventos.sinks.sink-hdfs.hdfs.rollSize = 0
eventos.sinks.sink-hdfs.hdfs.rollCount = 0

eventos.sinks.sink-hdfs.hdfs.batchSize = 100
eventos.sinks.sink-hdfs.hdfs.minBlockReplicas = 1

