services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: ecommerce-namenode
    restart: unless-stopped
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=ecommerce-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
    volumes:
      - namenode_data:/hadoop/dfs/name
    networks:
      - ecommerce-network

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: ecommerce-datanode
    restart: unless-stopped
    depends_on:
      - namenode
    ports:
      - "9864:9864"
      - "9866:9866"
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
      - HDFS_CONF_dfs_datanode_hostname=${HDFS_DATANODE_HOSTNAME}
      - SERVICE_PRECONDITION=namenode:9870
    volumes:
      - datanode_data:/hadoop/dfs/data
    networks:
      - ecommerce-network

volumes:
  namenode_data:
  datanode_data:

networks:
  ecommerce-network:
    driver: bridge