FROM flink:1.20.3-scala_2.12-java17

USER root

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-dev && \
    rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python

RUN pip3 install --no-cache-dir \
    apache-flink==1.20.3 \
    happybase

USER flink